// Generated by CoffeeScript 1.6.3
(function() {
  var send;

  send = require('./send');

  module.exports = function(req, res, next, msg, status) {
    if (typeof next !== 'function') {
      status = msg;
      msg = next;
      next = null;
    }
    if (msg) {
      if (msg.toString && typeof msg !== 'string') {
        msg = {
          error: msg.toString()
        };
      } else {
        msg = {
          error: msg
        };
      }
    } else {
      msg = {
        error: true
      };
    }
    if (next) {
      return send(req, res, next, msg, status || 400);
    } else {
      return send(req, res, msg, status || 400);
    }
  };

}).call(this);
