// Generated by CoffeeScript 1.6.3
(function() {
  var log_init, options, restify, routes;

  restify = require('restify');

  log_init = require('./log_init');

  options = require('./options');

  routes = require('./routes');

  module.exports = function(overrides, callback) {
    var server;
    if (callback == null) {
      callback = overrides;
    } else if (typeof overrides === 'object') {
      options.update(overrides);
    }
    server = restify.createServer();
    server.use(restify.acceptParser(server.acceptable));
    server.use(restify.queryParser());
    server.use(restify.bodyParser());
    server.use(log_init);
    server.pre(function(req, res, next) {
      req.headers.accept = 'application/json';
      return next();
    });
    return routes(server, function() {
      return server.listen(options.port, options.host, function() {
        console.log('listening @ ' + options.host + ':' + options.port);
        if (typeof callback === 'function') {
          return callback();
        }
      });
    });
  };

}).call(this);
