// Generated by CoffeeScript 1.6.3
(function() {
  var Log,
    __hasProp = {}.hasOwnProperty;

  Log = require('./log');

  module.exports = function(req, res, next) {
    var k, log, params, v, _ref;
    log = new Log(true);
    params = '';
    if (req.body != null) {
      _ref = req.body;
      for (k in _ref) {
        if (!__hasProp.call(_ref, k)) continue;
        v = _ref[k];
        params = JSON.stringify(req.body);
        break;
      }
    }
    log.push(req.method + ' ' + req.url + ' ' + params);
    req.__log = log;
    return next();
  };

}).call(this);
