// Generated by CoffeeScript 1.6.3
(function() {
  module.exports.host = 'localhost';

  module.exports.port = 80;

  module.exports.routes = './routes';

  module.exports.update = function(overrides) {
    var k, v, _results;
    _results = [];
    for (k in overrides) {
      v = overrides[k];
      _results.push(module.exports[k] = v);
    }
    return _results;
  };

}).call(this);
