// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(n, size) {
    if (size == null) {
      size = 2;
    }
    while (String(n).length < size) {
      n = '0' + n;
    }
    return n;
  };

}).call(this);
