// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(req, res, next, url) {
    var ms;
    if (typeof next !== 'function' || next === null) {
      url = next;
      next = null;
    }
    res.redirect(url);
    ms = (new Date).getTime() - req.__log.t.getTime();
    req.__log.push('(' + ms + 'ms) ' + res.statusCode + ' ' + url).push();
    if (next) {
      return next();
    }
  };

}).call(this);
