// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(req, res, next, msg, status) {
    var log;
    if (typeof next !== 'function' || next === null) {
      status = msg;
      msg = next;
      next = null;
    }
    res.send(status || 200, msg);
    log = 'HTTP' + res.statusCode + ' ' + JSON.stringify(msg);
    req.__log.push(log).flush();
    if (next) {
      return next();
    }
  };

}).call(this);
