// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(s, n) {
    var a;
    a = [];
    while (a.length < n) {
      a.push(s);
    }
    return a.join('');
  };

}).call(this);
