// Generated by CoffeeScript 1.6.3
(function() {
  var pad;

  pad = require('./pad');

  module.exports = function(date) {
    var offset;
    if (date == null) {
      date = new Date;
    }
    offset = date.getTimezoneOffset();
    return (offset > 0 ? '-' : '+') + pad(Math.abs(offset) / 60) + ':' + pad(Math.abs(offset) % 60);
  };

}).call(this);
