// Generated by CoffeeScript 1.6.3
(function() {
  var double_digit;

  double_digit = function(str) {
    if (str < 10) {
      str = '0' + str;
    }
    return str;
  };

  module.exports = function(date) {
    var d, h, i, m, s;
    if (date == null) {
      date = new Date;
    }
    m = double_digit(date.getMonth() + 1);
    d = double_digit(date.getDate());
    h = double_digit(date.getHours());
    i = double_digit(date.getMinutes());
    s = double_digit(date.getSeconds());
    return date.getFullYear() + '-' + m + '-' + d + ' ' + h + ':' + i + ':' + s;
  };

}).call(this);
